const ourTeamData = {
    backgroundImage: "/scc18.jpg",
    title: "Meet The Team",
    titleDescription: "An organization is only as strong as the people who are working toward the same purpose. Our clear mission unifies us, and their dedication and passion are wha make our organization thrive.",
    subTitle: "Who We Are",
    teamMembers: [
        {
            name: "Innocent Mbanda",
            position: "Co-Founder & CEO",
            picture: "https://media.licdn.com/dms/image/C5603AQFgfnu2ukzMOw/profile-displayphoto-shrink_200_200/0/1635430646520?e=2147483647&v=beta&t=uZ2XAS-woHmm39MBUs8XX_JVh7qkSO3KI0M_aBjBbjU",
            linkedIn: "https://www.linkedin.com/in/mbanda-innocent-a91737aa/",
            github: "",
            x: "",
            dribble: "",
            instagram: "",
        },
        {
            name: "Jean Jacque Iradukunda",
            position: "Co-Founder & COO",
            picture: "/jean-jacques.jpeg",
            linkedIn: "https://www.linkedin.com/in/jean-jacques-iradukunda-mdp-867aa1103/",
            github: "",
            x: "",
            dribble: "",
            instagram: "",
        },
        {
            name: "Lidia Solomon",
            position: "Program Manager",
            picture: "https://firebasestorage.googleapis.com/v0/b/shecancode-website.appspot.com/o/images%2Flidia-solomon.jpeg?alt=media&token=6b52bc67-5338-42a0-ae51-c82aa0c5f45f",
            linkedIn: "https://www.linkedin.com/in/lidia-solomon/",
            github: "",
            x: "",
            dribble: "",
            instagram: "",
        },
        {
            name: "Josiane Tuyisenge",
            position: "Finance Officer",
            picture: "/josiane.jpeg",
            linkedIn: "https://www.linkedin.com/in/josiane-tuyisenge-490a08311",
            github: "",
            x: "",
            dribble: "",
            instagram: "",
        },
        {
            name: "Liliane Uwase",
            position: "HR & Operations Manager",
            picture: "https://media.licdn.com/dms/image/D4E03AQEOWYWX-_WX_Q/profile-displayphoto-shrink_200_200/0/1686306845073?e=2147483647&v=beta&t=dEGAWexroP3JXk8w8h0d4GG3Hv5dkBYp0_ueFFA2HxY",
            linkedIn: "https://www.linkedin.com/in/liliane-uwase-28b138182/",
            github: "",
            x: "",
            dribble: "",
            instagram: "",
        },
        {
            name: "Esther Beza Byizigiro",
            position: "Admission & Student Success and M&E Coordinator",
            picture: "https://firebasestorage.googleapis.com/v0/b/shecancode-website.appspot.com/o/images%2Festher-beza.jpeg?alt=media&token=13c2c435-3ffb-4174-b764-eeec6a2a3df6",
            linkedIn: "https://www.linkedin.com/in/esther-beza-byizigiro-939b3834a/",
            github: "",
            x: "",
            dribble: "",
            instagram: "",
        },
        {
            name: "Phiona Uwera",
            position: "Communication Officer",
            picture: "https://firebasestorage.googleapis.com/v0/b/shecancode-website.appspot.com/o/images%2Fphiona.JPG?alt=media&token=d49e4979-6493-4ba5-9f1a-919016973621",
            linkedIn: "https://www.linkedin.com/in/uwera-phiona-14a5162b6",
            github: "",
            x: "",
            dribble: "",
            instagram: "",
        },
        {
            name: "Yves Manzi",
            position: "Grant Writer",
            picture: "https://firebasestorage.googleapis.com/v0/b/shecancode-website.appspot.com/o/images%2FYves-manzi.JPG?alt=media&token=53587a2c-5c89-408c-91f9-e6016b6ddd02",
            linkedIn: "https://www.linkedin.com/in/yves-manzi-812609350/",
            github: "",
            x: "",
            dribble: "",
            instagram: "",
        },
        {
            name: "Jean Eric Hirwa",
            position: "Head of Academics, Senior Tainer & Fullstack Developer",
            picture: "/jean-eric.jpeg",
            linkedIn: "https://www.linkedin.com/in/jean-eric-hirwa/",
            github: "",
            x: "",
            dribble: "",
            instagram: "",
        },
        {
            name: "Axelle Ineza",
            position: "Senior Trainer & Fullstack Developer",
            picture: "/axelle.jpeg",
            linkedIn: "https://www.linkedin.com/in/ineza-axelle-b3762a224",
            github: "",
            x: "",
            dribble: "",
            instagram: "",
        },
        {
            name: "Cates Nsengiyumva",
            position: "Junior Trainer & Fullstack Developer",
            picture: "/cates.jpeg",
            linkedIn: "https://www.linkedin.com/in/cates-nsengiyumva-472975174",
            github: "",
            x: "",
            dribble: "",
            instagram: "",
        },
    ]
}

export default ourTeamData;
